### ISSUE TITLE
Warning при установке через composer: Ambiguous class resolution, "App\AppException"

### ISSUE THREAD

**Issue by Leonid74** [andrey-tech/bitrix24-api-php#1]
Добрый день!

Спасибо за нормальную API к Битрикс24!

Есть и маленькая проблемка: При установке с помощью композера появляется предупреждение:
Warning: Ambiguous class resolution, "App\AppException" was found 2x: in "D:/L/OneDrive/Dev/MyWebSites/Profadmin/b24api.profadmin.ru.loc/vendor/andrey-tech/http-client-php/src/App/AppException.php" and "D:/L/OneDrive/Dev/MyWebSites/Profadmin/b24api.profadmin.ru.loc/vendor/andrey-tech/debug-logger-php/src/App\AppException.php", the first will be used.

Я так понимаю, для работы оно мешать не будет, но лучше бы пофиксить в будущих релизах.

Еще вопрос - планируется ли добавление методов для работы с лидами? Очень востребовано...

**Comment by andrey-tech** [comment]
Добрый день!

> Есть и маленькая проблемка: При установке с помощью композера появляется предупреждение:
Warning: Ambiguous class resolution

Спасибо, в ближайшее время запланировано исправление `andrey-tech/http-client-php` и `andrey-tech/debug-logger-php`.

> Еще вопрос - планируется ли добавление методов для работы с лидами? Очень востребовано...

Да, планируется.

**Comment by Leonid74** [comment]
Отлично, спасибо!
