### ISSUE TITLE
Появится ли реквизиты в библиотеке?

### ISSUE THREAD

**Issue by lacoste-sochi** [andrey-tech/bitrix24-api-php#11]
Хочу поблагодарить за отличную проделанную работу. Документация и реализация на высшем уровнем!!!

Очень не хватает реквизитов,например создал компании и хочу прикрепить ИНН. Будет ли дорабатываться решение?

Спасибо Вам за труды! =)

**Comment by andrey-tech** [comment]
Добрый день!

В связи с низкой востребованностью, добавление функциональности работы с реквизитами в ближайшее время не планируется.
