### ISSUE TITLE
Поиск по массиву значений

### ISSUE THREAD

**Issue by lacoste-sochi** [andrey-tech/bitrix24-api-php#12]
Здравствуйте, как организовать поиск по массиву значений?

https://dev.1c-bitrix.ru/rest_help/crm/auxiliary/duplicates/crm_duplicate_findbycomm.php
В оф. документации есть такой метод, но позволяет по 20 элементов, что такое себе...

Может можно как то поиск организовать в батчи на = в фильтре? Или как лучше искать? Возможно ли как то проще с этой библиотекой? 

Спасибо!

**Comment by andrey-tech** [comment]
Добрый день!

Ограничение в 20 элементов понятно и вызвано нежеланием перегружать серверы Bitrix. И это ограничение не обойти.

Поэтому остаётся только вариант "в лоб", предполагающий пакетную выгрузку всех сущностей и самостоятельный поиск  телефонов или email-адресов по массиву значений. А как именно лучше искать зависит от того что вы ищите.

**Comment by lacoste-sochi** [comment]
> Добрый день!
> 
> Ограничение в 20 элементов понятно и вызвано нежеланием перегружать серверы Bitrix. И это ограничение не обойти.
> 
> Поэтому остаётся только вариант "в лоб", предполагающий пакетную выгрузку всех сущностей и самостоятельный поиск телефонов или email-адресов по массиву значений. А как именно лучше искать зависит от того что вы ищите.

Спасибо за ответ, и за чудесную библиотеку. Да,скорее всего так и придется мне с Select выдергивать телефоны,емайл,и ID. Быстрым методом, а там уже своя логика.

Успехов Вам! =) Спасибо что пишите решения на общее пользование
