### ISSUE TITLE
Предложение. Добавление методов работающих с информационными блоками Б24 (не CRM)

### ISSUE THREAD

**Issue by AlexandreZaytsev** [andrey-tech/bitrix24-api-php#13]
аналогично тикету [по js обертке](https://github.com/andrey-tech/bx24-wrapper-js/issues/3)

Добрый день.
с модулем CRM и его методами все понятно - все работает...
но модуль этот в свою очередь 'собран/построен' из инфоблоков Б24 которые имеют свою структуру и свои методы - отличные от CRM...

в частности: 
1. по каталогу, catalog.product.list в результатах, отдается именованный объект products содержащий массив данных (в CRM сразу массив)
2. сам синтаксис полей идет в нижнем регистре (в CRM в верхнем)

судя по всему (по состоянию на 2023 год) Б24 оптимизирует инфоблоки добавляя новые методы..., - для того же каталога пошла градация на
catalog.product.sku.list
catalog.product.offer.list
catalog.product.service.list
с оптимизацией запросов
...
развиваются короче куда-то

Просьба: - добавьте пожалуйста в PHP обертку функционал позволяющий работать с данными методами (не обязательно адресный в плане для каждого метода/сущности конкретный, можно просто в 'ядро'... не знаю как лучше)

ps
хотя если смотреть в целом:
1- модуль CRM это только частный случай в общей структуре данных Б24...
2- много людей уже используют Вашу обертку...
как поступить - переделать все или 'пофиксить' часть... - не знаю ))) 

Спасибо

**Comment by andrey-tech** [comment]
Александр, добрый день!

Тут действуем по аналогичной схеме, что и в [js-библиотеке](https://github.com/andrey-tech/bx24-wrapper-js/issues/3). В рамках ветки [issue-13](https://github.com/andrey-tech/bitrix24-api-php/tree/issue-13) добавил в методы "ядра" в классе `Bitrix24API` необязательные параметры `dataExtractor` и `idKey`. Проверьте работу новых методов каталога Битрикс24 с измененными методами "ядра": `getList()`, `fetchList()`, `batchRequest()`.

**Comment by andrey-tech** [comment]
@AlexandreZaytsev Удалось проверить работу измененных методов?

**Comment by andrey-tech** [comment]
В отсутствие какой-либо обратной связи в разумное время, закрываю данный issue.
