### ISSUE TITLE
Работа со счетами (смарт процессами) (feature request)

### ISSUE THREAD

**Issue by rasxod** [andrey-tech/bitrix24-api-php#14]
Столкнулся с тем что нужны счета из сделки
в принципе если бы вы добавили то было бы круто там всего-то и делов 
1 добавить класс для работы со счетами(а в принципе со смарт процессами)
2 в параметры добавить идентификатор процесса
![image](https://github.com/andrey-tech/bitrix24-api-php/assets/5847571/1cd6cb33-83a2-436b-b1a7-04f3300f34c1)

**Comment by andrey-tech** [comment]
Добрый день!

В настоящее время не работаю над проектами, связанными с Битрикс24. Поэтому, не имея аккаунтов в Битрикс24, не могу вести разработку. Не могли бы Вы создать pull request, включающий необходимые Вам доработки, касающиеся счетов из сделки?

**Comment by rasxod** [comment]
ок тоггда я в конце проекта запилю вам изменения

**Comment by andrey-tech** [comment]
> ок тоггда я в конце проекта запилю вам изменения

Жаль, что за прошедший год так ничего и не получилось.
