### ISSUE TITLE
Загрузка файлов на диск

### ISSUE THREAD

**Issue by nikolablin** [andrey-tech/bitrix24-api-php#15]
Добрый день.
Возможно ли как-то оптимизировать загрузку больших файлов на диск? У меня обучающие видео на примонтированном диске, которые нужно копировать в папку в битрикс, средним размером по 1,5 Гб.

**Comment by andrey-tech** [comment]
Добрый день!

Используемый библиотекой REST API Bitrix24 не имеет каких-либо возможностей по оптимизации загрузки файлов на диск. Ситуация усугубляется ещё и тем, что файл может быть загружен через API только будучи закодированным в Base64, а это увеличивает размер передаваемых данных на 33%. 

См. https://dev.1c-bitrix.ru/rest_help/disk/folder/disk_folder_uploadfile.php

**Comment by nikolablin** [comment]
Спасибо. Значит будем искать другое решение.
