### ISSUE TITLE
Работа с методом getContactsByPhone

### ISSUE THREAD

**Issue by nikolablin** [andrey-tech/bitrix24-api-php#16]
Добрый день.

Пробую методом getContactsByPhone получить контакт,
но возвращается пустой массив:

```
    try {
      $webhookURL = 'https://***/rest/20/***/';
      $bx24 = new Bitrix24API($webhookURL);

      $contacts = $bx24->getContactsByPhone($clientPhone,['ID','NAME']);

      print_r($contacts);

    } catch (Bitrix24APIException $e) {
        printf('Ошибка (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
    } catch (Exception $e) {
        printf('Ошибка (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
    }

```

Проверяю тот же номер в Битриксе, есть клиент.

**Comment by andrey-tech** [comment]
Добрый день!

Поиск телефона выполняется по точному совпадению.
Попробуйте загузить контакт методом `getContact()` и посмотреть в каком виде возвращается номер телефона.

**Comment by nikolablin** [comment]
Да, по точному совпадению все работает. Спасибо за помощь)
