### ISSUE TITLE
Ошибка #77 curl после 300 запроса

### ISSUE THREAD

**Issue by nikolablin** [andrey-tech/bitrix24-api-php#17]
Добрый день.
Для обновления контактов использую метод getContactsByPhone.
Контактов много и запросов приходится делать много. Но после 300 запроса вылетаю в ошибку 
`HTTP: Ошибка cURL #77 (https://bitrix.autocity-finance.ru/rest/20/**/crm.contact.list.json):`

**Comment by andrey-tech** [comment]
Добрый день!

1) Ошибка cURL [#77](https://curl.se/libcurl/c/libcurl-errors.html) связана с файлом корневых сертификатов `cacert.pem`: "CURLE_SSL_CACERT_BADFILE (77) Problem with reading the SSL CA cert (path? access rights?)".

2) Попробуйте обновить библиотеку [andrey-tech/http-client-php](https://github.com/andrey-tech/http-client-php) до версии v3.0.7. Она содержит актуальную на сегодня версию файла корневых серификатов `cacert.pem`.

**Comment by nikolablin** [comment]
Добрый день.
Обновил библиотеку, composer сейчас выглядит как:
![image](https://github.com/andrey-tech/bitrix24-api-php/assets/26625219/e60e8909-9705-46c5-816d-43198803cab9)

Ошибка сохранилась та же.

**Comment by andrey-tech** [comment]
Из вашего скриншота непонятно какая версия библиотеки `andrey-tech/http-client-php` реально установлена. Проверьте версию библиотеки в `composer.lock` или убедитесь, что сертификаты в файле `cacert.pem` этой библиотеки датированы декабрём 2023 года.

**Comment by nikolablin** [comment]
Проверил, все так, как указано выше:
Версия cacert.pem - декабрь 2023
![image](https://github.com/andrey-tech/bitrix24-api-php/assets/26625219/8412e387-da31-4d5d-bfe2-00c4d57626d1)

Версия http-client-php - 3.0.7
![image](https://github.com/andrey-tech/bitrix24-api-php/assets/26625219/88af9f52-02f3-4c01-9a09-cbc4687b9bde)

**Comment by thwipthwipx** [comment]
Аналогичная проблема, версия библиотеки andrey-tech/http-client-php 3.0.7

**Comment by andrey-tech** [comment]
@nikolablin
Давайте попробуем разобраться что происходит.
1) Ошибка cURL #77 происходит всегда после 300 запроса?
2) Ошибка cURL #77 происходит только при вызове метода `getContactsByPhone`?
3) Имеется ли какой-то дополнительный текст после двоеточия в сообщении об ошибке? `HTTP: Ошибка cURL #77 (https://bitrix.autocity-finance.ru/rest/20/**/crm.contact.list.json):`.
4) Попробуте добавить задержку между запросами, скажем, в 1 секунду и посмотрите возникнет ли ошибка после 300 запроса.

**Comment by nikolablin** [comment]
1. Да, всегда после 300
2. Да, другие методы отрабатывают. Только с этим проблема
3. Нет, текста другого нет. Печатал развернуто ошибку, получил путь к выполнению метода в классе.
4. Задержку в первую очередь пробовал добавить, секунд 20. Но ошибка все равно начиналась там же, на 300 запросе.

**Comment by andrey-tech** [comment]
Попробуйте **временно** отключить проверку SSL/TLS-сертификата сервера и посмотреть будет ли возникать ошибка:
```php
$bx24->http->verifySSLCertificate = false;
```

**Comment by nikolablin** [comment]
Отключил. На 300 запросе теперь летит ошибка Ошибка cURL #35 (https://bitrix.autocity-finance.ru/rest/*/***/crm.contact.list.json): Process open FD table is full

**Comment by andrey-tech** [comment]
Видимо столкнулись с проблемой с cURL, описанной тут: https://github.com/php-http/curl-client/issues/38
Предлагается, в частности, попробовать увеличить величину `ulimit`. Надеюсь у вас GNU/Linux ;)

**Comment by nikolablin** [comment]
Попробую передать в Хэдер connection:close на 300 запросе и увеличить ulimit. Отпишусь.

**Comment by thwipthwipx** [comment]
У меня cURL #77 возникала в методе `featchDealList`. Увеличение ulimit решило проблему. Спасибо

**Comment by nikolablin** [comment]
Увеличил ulimit, не помогло. 
Connection close не могу интегрировать без вмешательства в библиотеку.

**Comment by andrey-tech** [comment]
@thwipthwipx 
>У меня cURL #77 возникала в методе featchDealList. Увеличение ulimit решило проблему. Спасибо

Расскажите как, где и насколько вы увеличили `ulimit`. Может быть это кому-то поможет.

**Comment by andrey-tech** [comment]
@nikolablin 
> Увеличил ulimit, не помогло.
> Connection close не могу интегрировать без вмешательства в библиотеку.

Попробуйте сделать **временные** изменения в `vendor`, чтобы проверить результат.

**Comment by nikolablin** [comment]
Добавил в $requestHeaders Connection: close на каждый запрос и все отлично прошло сразу. 
Быть может можно передавать этот хэдер сразу из $bx24? Чтоб не закрывать каждый раз, а по счетчику?

**Comment by andrey-tech** [comment]
Поскольку для каждого запроса вызывается `curl_init()`, а после обработки ответа - `curl_close()`, то есть соединение не персистентное, то разумно с каждым запросом передавать HTTP-заголовок `Connection: close`.

**Comment by nikolablin** [comment]
Окей, тогда оставлю его там на постоянку. Спасибо за помощь)
