### ISSUE TITLE
Консультация

### ISSUE THREAD

**Issue by devcodex2025** [andrey-tech/bitrix24-api-php#4]
Можно с Вами как-то связаться, по поводу использования библиотеки Bitrix24 API или консультации по улучшению своего скрипта?

**Comment by andrey-tech** [comment]
Добрый день!
Не стесняйтесь и смело пишите сюда свои вопросы по поводу использования библиотеки Bitrix24 API или улучшению своего скрипта. По каждому новому вопросу создавайте отдельный Issue. Возможно кто-то ещё захочет и сможет вам помочь.

**Comment by devcodex2025** [comment]
Я столкнулся с проблемой получения значения списочного поля. Эти значения нужно получить и выбрать из них нужное. Использовал метод - crm.deal.userfield.get, но вместо значений, получил название поля.

**Comment by andrey-tech** [comment]
Покажите, что вы получаете в ответе от метода `crm.deal.userfield.get`. Все возможные значения списочного поля должны возвращаться в массиве LIST ответа.

**Comment by devcodex2025** [comment]
![Снимок экрана 2021-04-08 083158](https://user-images.githubusercontent.com/67425372/113973398-f032ef00-9844-11eb-8f20-c821c4948df2.png)

**Comment by andrey-tech** [comment]
В пользовательском поле типа "список" (в списочном поле) в ответе метода должно возвращаться `"USER_TYPE_ID": "enumeration"`, а в массиве LIST - список всех возможных значений поля, а у вас возвращается что-то иное. Проверьте тип пользовательского поля или создайте новое поле нужного вам типа "список".

**Comment by devcodex2025** [comment]
Тип поля - привязка к элементам инфоблока

**Comment by andrey-tech** [comment]
> Тип поля - привязка к элементам инфоблока

Поэтому в ответе метода `crm.deal.userfield.get` вы не получаете список возможный значений.
Попробуйте поискать решение здесь: [https://dev.1c-bitrix.ru/support/forum/forum48/topic120331/](https://dev.1c-bitrix.ru/support/forum/forum48/topic120331/).

**Comment by devcodex2025** [comment]
Хороший совет, только тип инфоблока пустой, там ничего нет, я указывал пустой в запросе, ошибка, Id блока я знаю, получается этот список из стороннего приложения в битрикс24, битрикс24 мойсклад, пока что не понимаю как правильно прописать тип и как присвоить ему нужное значение, имеется ввиду это поле. Также вопрос, как лучше присваивать сделке уже существующие товары, возможно у Вас есть наработки.

**Comment by andrey-tech** [comment]
> Также вопрос, как лучше присваивать сделке уже существующие товары, возможно у Вас есть наработки

Воспользуейтесь методом `setDealProductRows()` библиотеки Bitrix24 API.

> пока что не понимаю как правильно прописать тип и как присвоить ему нужное значение, имеется ввиду это поле.

Тут надо пробовать разные варианты. К библиотеке Bitrix24 API это отношения не имеет.
