### ISSUE TITLE
Получение списка лидов

### ISSUE THREAD

**Issue by ghost** [andrey-tech/bitrix24-api-php#6]
Добрый день. 
Пытаюсь использовать Вашу библиотеку для формирования статистики получения лидов и сделок. 
Застопорился практически в самом начале.

Пытаюсь получить список лидов, отфильтровав их по дате.

```
    try {
        $webhookURL = 'Webhook URL';
        $bx24 = new Bitrix24API($webhookURL);

        // Устанавливаем максимальный уровень вывода отладочных сообщений в STDOUT
        $bx24->http->debugLevel = HTTP::DEBUG_URL |  HTTP::DEBUG_HEADERS | HTTP::DEBUG_CONTENT;

        // Устанавливаем троттлинг запросов на уровне не более 1 запроса в 2 секунды
        $bx24->http->throttle = 0.5;

        // Устанавливаем таймаут обмена данными в 30 секунд
        $bx24->http->curlTimeout = 30;

        // Получаем компанию по ID
        $filter = array();
        $filter[htmlentities('>DATE_CREATE')] = date('Y-m-d\T00:00:00');
        $filter[htmlentities('<DATE_CREATE')] = date('Y-m-d\T23:59:59');

        $generator = $bx24->fetchLeadList($filter);
        foreach ($generator as $leads) {
            foreach($leads as $lead) {
              print_r($lead);
            }
        }

    } catch (Bitrix24APIException $e) {
        printf('Ошибка (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
    } catch (Exception $e) {
        printf('Ошибка (%d): %s' . PHP_EOL, $e->getCode(), $e->getMessage());
    }

```

В итоге получаю в ответе все лиды нашей CRM. Ничего не могу понять, что не так.

**Comment by andrey-tech** [comment]
Добрый вечер! 

А `htmlentities()` зачем!?

Посмотрите в [примерах из документации](https://dev.1c-bitrix.ru/rest_help/crm/leads/crm_lead_list.php) Битрикс24 как правильно конструировать условия фильтрации.

**Comment by ghost** [comment]
> Добрый вечер!
> 
> А `htmlentities()` зачем!?
> 
> Посмотрите в [примерах из документации](https://dev.1c-bitrix.ru/rest_help/crm/leads/crm_lead_list.php) Битрикс24 как правильно конструировать условия фильтрации.

Без них символ "<" не читается в ключе элемента массива.

Посмотрел пример, сделал аналогично. На выходе все равно получаю не те лиды. Попробовал преобразовывать из объекта в массив, чтобы точно получить нужные имена полей в массиве. Не помогло.

```
        $filter = (object)array();
        $filter->{htmlentities('>DATE_CREATE')} = date('Y-m-d\T00:00:00');
        $filter->{htmlentities('<DATE_CREATE')} = date('Y-m-d\T23:59:59');
        $filter = (array)$filter;

        $generator = $bx24->fetchLeadList($filter, array('ID','DATE_CREATE'));

```

**Comment by ghost** [comment]
Вот такой запрос и ответ. Но лиды не за те даты все равно:
`[1] ===> POST https://bitrix.autocity-crm.ru/rest/20/**/crm.lead.list.json POST /rest/20/**/crm.lead.list.json HTTP/2 Host: bitrix.autocity-crm.ru user-agent: HTTP-client/3.x.x accept: */* content-length: 201 content-type: application/x-www-form-urlencoded order%5BID%5D=ASC&filter%5B%26gt%3BDATE_CREATE%5D=2022-02-01T00%3A00%3A00&filter%5B%26lt%3BDATE_CREATE%5D=2022-02-01T23%3A59%3A59&filter%5B%3EID%5D=0&select%5B0%5D=ID&select%5B1%5D=DATE_CREATE&start=-1 [1] <=== RESPONSE 0.3347s (200) HTTP/2 200 server: nginx date: Tue, 01 Feb 2022 07:06:09 GMT content-type: application/json; charset=utf-8 content-length: 3082 vary: HTTPS p3p: policyref="/bitrix/p3p.xml", CP="NON DSP COR CUR ADM DEV PSA PSD OUR UNR BUS UNI COM NAV INT DEM STA" x-powered-cms: Bitrix Site Manager (0d5cd18d9cc32b337bfb75062b47bcab) expires: Thu, 19 Nov 1981 08:52:00 GMT cache-control: no-store, no-cache, must-revalidate pragma: no-cache x-ammina-module: smtp access-control-allow-origin: * access-control-allow-headers: origin, content-type, accept x-content-type-options: nosniff set-cookie: BITRIX_SM_SALE_UID=0; expires=Fri, 27-Jan-2023 07:06:09 GMT; Max-Age=31104000; path=/ x-content-type-options: nosniff x-frame-options: SAMEORIGIN`

**Comment by andrey-tech** [comment]
Не надо ничего усложнять, просто запишите условие фильтрации аналогично тому, как это сделано в [примере из документации](https://dev.1c-bitrix.ru/rest_help/crm/leads/crm_lead_list.php) Битрикс24 (ключ `filter`):
```php
$result = CRest::call(
    'crm.lead.list',
    [
        'filter' => [
            '>DATE_CREATE' => '2019-10-01T00:00:00',
            '<DATE_CREATE' => '2019-10-31T23:59:59'
        ],
        'select' => [
            'ID',
            'DATE_CREATE'
        ]
    ]
);
```

**Comment by ghost** [comment]
Удивительно, но сработало. Спасибо за помощь
