### ISSUE TITLE
Долгая доставка ответа при запросе

### ISSUE THREAD

**Issue by nikolablin** [andrey-tech/bitrix24-api-php#7]
Добрый день. 
Через вашу библиотеку получаю лиды из битрикса для сведения статистики.
Возникла проблема со временем. Очень долго получаю ответ, если делаю выборку за срок больше одного дня.

Например при запросе:
`$generator = $bx24->fetchLeadList(array('>DATE_CREATE' => '2022-02-01T00:00:00', '<DATE_CREATE' => '2022-02-04T23:59:59'),array('TITLE','STATUS_ID'),array('DATE_CREATE'));`

Время ответа занимает 1,5-2 минуты и в ответе лежит 160 лидов.

**Comment by andrey-tech** [comment]
Добрый день!

Установите максимальный уровень вывода отладочных сообщений и включите логирование запросов/ответов к серверу Битрикс24 в файл. Сделайте ваш "долгий" запрос и посмотрите время ответа от сервера Битрикс24 и какие запросы/ответы происходят. Возможно просто ваш сервер Битрикс24 долго отвечает на запросы.

**Comment by andrey-tech** [comment]
В отсутствии обратной связи закрываю данный issue.

**Comment by nikolablin** [comment]
Извиняюсь за долгий ответ.
Да, проблема оказалась в нашем сервере, решаем на своей стороне.
Спасибо.
